name: Build webhooks-poster
run-name: ${{ github.ref}}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  project: ${{toJson('["A", "B", "C"]')}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: aws s3api head-object --bucket
      - run: echo 1
        if: ${{ failure() }}
      - run: echo 2
