name: Build webhooks-poster
run-name: ${{ github.ref}}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  testa:
    strategy:
      matrix:
        package: [A, B, C]
    runs-on: ubuntu-latest
    steps:
      # output what you want, the output of package B will be available in needs for furture jobs
      - run: echo "${{matrix.package}}=true" > $GITHUB_OUTPUT
        id: mystep
    outputs:
      project: ${{ toJson(steps.mystep.outputs) }}
  testb:
    runs-on: ubuntu-latest
    needs: testa
    steps:
      - run: echo ${{ needs.testa.outputs.project }}
